### ISSUE TITLE
Product names, grammar, and organization need improvements on first and second pages of website.

### ISSUE THREAD

**Issue by susanmdouglas-aws** [babelfish-for-postgresql/babelfish_project_website#89]
There are problems with: https://babelfishpg.org/docs/vision/ and https://babelfishpg.org/docs/contributing/ that need to be addressed, including, but not limited to:

Bad sentence:  In fact, migrating data to PostgreSQL can be relatively easy, while migration entire application stacks can be really difficult.

Product name and style: You can move away from expensive MS SQL deployments without doing a painful app migration. Brilliant, isn’t it?

Justifying our limitations?: There is code (especially some server-side procedures related to administration) that is not going to work on Babelfish. The reason is that every database engine has limitations. 

Editing (end with reach out, and remove 'to the community': Be part of the community and help to improve Babelfish even more. If you want to contribute to Babelfish simply reach out to the community.

Editing (should probably be limitations or incompatibilities, but not both): We have dedicated an entire section dealing with limitations incompatibilities.

Editing (bad segue - remove these three sentences): If you add new features, you also need to add tests for functionality. Patches that do not contain tests for new features will not be accepted by the community. The same is true for missing documentation.

**Comment by laurenz** [comment]
- About justifying our limitations: yes, that's exactly what that is.
  Is that bad? If yes, then the whole paragraph except the first sentence should go.

- About the double "community": ending a sentence with "reach out" sounds like slang in my ears (but I am no native speaker).
  I have changed it to "reach out to us".

- "limitations incompatibilities": Since "incompatibility" reminds of "compatibility", which I have been told is undesirable, I went with "We have dedicated an entire section to the limitations".

- Bad segue: I didn't remove the sentences, because they contain important information. Rather, I rewrote the text and moved the parts that deal with tests to the previous section.
